"use client";
import { useState } from "react";
import type { AiRequestConfig, AnalyzeRequestBody } from "@/lib/types";
import { ProviderConfig } from "./ProviderConfig";
import { ResumeCard } from "./ResumeCard";
import { DesperationSelector } from "./DesperationSelector";
interface Props { onAnalyze: (data: AnalyzeRequestBody) => void; isLoading?: boolean; error?: string; }
export function InputSection({ onAnalyze, isLoading, error }: Props) {
  const [config, setConfig] = useState<AiRequestConfig>({ provider: "openai", apiKey: "", model: "gpt-4o-mini" }); const [resumeText, setResumeText] = useState(""); const [jobDescription, setJobDescription] = useState(""); const [linkedinUrl, setLinkedinUrl] = useState(""); const [githubUrl, setGithubUrl] = useState(""); const [desperationLevel, setDesperationLevel] = useState(2); const [validationError, setValidationError] = useState(""); const inputClass = "field-control";
  function handleSubmit(e: React.FormEvent) { e.preventDefault(); setValidationError(""); if (!config.apiKey.trim()) return setValidationError("API key is required. This app runs on your key."); if (!resumeText.trim()) return setValidationError("Resume is required. Paste text or upload a PDF."); if (!jobDescription.trim()) return setValidationError("Job description is required."); onAnalyze({ config, resumeText, jobDescription, linkedinUrl: linkedinUrl.trim() || undefined, githubUrl: githubUrl.trim() || undefined, desperationLevel }); }
  return <form onSubmit={handleSubmit} className="workflow-wrap"><section id="analyzer" className="workflow-card scroll-mt-24"><div className="workflow-heading"><span className="step-badge">1</span><h2>Let&apos;s get to know you <span>(and your career trauma)</span></h2></div><div className="input-grid"><div className="input-pane"><ResumeCard value={resumeText} onChange={setResumeText} disabled={isLoading} /></div><div className="input-pane"><label htmlFor="jobDescription" className="field-label">Job Description</label><textarea id="jobDescription" value={jobDescription} onChange={(e) => setJobDescription(e.target.value)} disabled={isLoading} placeholder="Paste the job description here..." rows={10} className={`${inputClass} jd-input`} /><p className="field-help">The more yapping, the better we can roast.</p></div></div><div className="social-row"><div><label htmlFor="linkedin" className="field-label">LinkedIn Profile <em>(optional)</em></label><input id="linkedin" value={linkedinUrl} onChange={(e) => setLinkedinUrl(e.target.value)} disabled={isLoading} placeholder="linkedin.com/in/yourprofile" className={inputClass} /></div><div><label htmlFor="github" className="field-label">GitHub Profile <em>(optional)</em></label><input id="github" value={githubUrl} onChange={(e) => setGithubUrl(e.target.value)} disabled={isLoading} placeholder="github.com/username" className={inputClass} /></div></div><div className="config-card"><ProviderConfig config={config} onChange={setConfig} compact /></div><div className="workflow-heading desperate-heading"><span className="step-badge">2</span><div><h2>How desperate are we?</h2><p>Honesty is optional. Results will vary.</p></div></div><DesperationSelector value={desperationLevel} onChange={setDesperationLevel} />{(validationError || error) && <div className="form-error">{validationError || error}</div>}<div className="action-row"><button type="submit" disabled={isLoading} className="cta-primary action-primary">✦ Analyze My Employment Aura <span>→</span></button><button type="button" onClick={() => document.getElementById("translator")?.scrollIntoView({ behavior: "smooth" })} className="cta-secondary">文&nbsp; JD Translator Only</button></div><p className="privacy-note">♙ We don&apos;t store your data. Your API key stays yours. Forever.</p></section></form>;
}
